name: Sync Strava TCX

on:
  schedule:
    - cron: '0 * * * *'  # Co godzinę
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Strava sync script
      env:
        STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
        STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
      run: python strava_sync_tcx_env.py

    - name: Dołącz pliki jako artifact
      uses: actions/upload-artifact@v4
      with:
        name: strava-results
        path: |
          *.tcx
          summary.txt